### ISSUE TITLE
Hoe fails on MRI Ruby trunk, or with Psych 4.0

### ISSUE THREAD

**Issue by halostatue** [seattlerb/hoe#112]
Psych 4.0 (included with MRI 3.1 trunk) has made two changes that are incompatible with the way that Hoe uses `YAML.load_file` at [hoe.rb:908-914](https://github.com/seattlerb/hoe/blob/7d2c140d5989129531d3972266d105a33b079502/lib/hoe.rb#L908-L914).

1. `YAML.load_file` now means `YAML.safe_load_file`, and
2. No builtin classes are supported by default.

In particular, because Regexp is a permitted value for one of the `.hoerc` configuration values, `YAML.load_file` should be replaced with:

```ruby
    homeconfig = exists ? YAML.safe_load_file(rc, permitted_classes: [Regexp]) : {}
```

Depending on _which_ versions of Ruby supported, this will probably need to be made a little more complex. I was trying to deal with this in one of the gems that I maintain and it appears that Ruby 2.4 includes Psych 2.x and Ruby 2.5 includes Psych 3.x, but at a version that doesn’t recognize `permitted_classes` as a valid key. I had wanted to do something like:

```ruby
if Gem::Version.new(YAML::VERSION) < Gem::Version.new('3.0')
  YAML.safe_load_file(rc, [Regexp])
else
  YAML.safe_load_file(rc, permitted_classes: [Regexp])
end
```

Instead, I’m having to do the following:

```ruby
def safe_load_yaml(filename)
  YAML.safe_load_file(rc, permitted_classes: [Regexp])
rescue
  YAML.safe_load_file(rc, [Regexp])
end
```

Although my class list is different.

```
Psych::DisallowedClass: Tried to load unspecified class: Regexp
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find'
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
…
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych.rb:334:in `safe_load'
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych.rb:587:in `block in safe_load_file'
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych.rb:586:in `open'
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych.rb:586:in `safe_load_file'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/ruby/3.1.0/gems/hoe-3.23.0/lib/hoe.rb:914:in `with_config'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/ruby/3.1.0/gems/hoe-3.23.0/lib/hoe.rb:402:in `activate_plugins'
/home/runner/work/ruby-mime-types/ruby-mime-types/vendor/bundle/ruby/3.1.0/gems/hoe-3.23.0/lib/hoe.rb:392:in `spec'
…
```

I’m going to try to resolve this in my case by specifying a development dependency on Psych of `~> 3.0`, which should smooth over all of the issues on my side, but this is an imperfect solution _at best_.

**Comment by halostatue** [comment]
`permitted_classes` as a keyword parameters was added in Psych 3.1, so if you wanted to use `Gem::Version`, you could do so.

**Comment by zenspider** [comment]
Just got hit by this. 😛

What I did:

```ruby
p psych:[Psych::VERSION, YAML.respond_to?(:safe_load_file)]
```

What I see:

```ruby
{:psych=>["3.0.2", false]}
{:psych=>["3.1.0", false]}
{:psych=>["3.1.0", false]}
{:psych=>["3.3.2", true]}
{:psych=>["4.0.3", true]}
```

so, it looks like 3.0 and 3.1 can both use the keyword arg and all I need to do is detect if `safe_load_file` is there (and call it directly?).

I've got this ready to go and it passes on all versions:

```ruby
  def maybe_load_yaml path
    if File.exist? path then
      if YAML.respond_to? :safe_load_file then
        YAML.safe_load_file path, permitted_classes: [Regexp, Symbol]
      else
        YAML.load_file path
      end
    else
      {}
    end
  end
```

**Comment by zenspider** [comment]
This seems to be back on track... closing. Release soonish.
