### ISSUE TITLE
Request: add helpful description and version to sow

### ISSUE THREAD

**Issue by velle** [seattlerb/hoe#115]
I am very noob in Ruby and struggling with a lot of concepts at the same time. I stumbled into some tutorial that used `sow` in bash. I happened to already have hoe installed, meaning that sow was actually present, though I did not even understand what hoe was. So what is sow?

I tried the classic `man` and `-h` but it doesnt really tell what sow is or does, and it does not tell that its part of hoe. 

```
$ sow -h
Usage: sow [options] project_name
Standard options:
    -t, --trunk                      Add project to subdir under 'trunk'.
    -d, --dev                        Add project to subdir under 'dev'.
    -s, --style style                Use template <style>.
    -h, --help                       Show this message.
```

Considering the mission of hoe, one of which is making it clear exactly "what is inside", I think sow should somehow reveal a bit more about itself :)

Also, there is no way of getting sow to tell it's version number. 

Best regards.

**Comment by zenspider** [comment]
ruby doesn't do man very well, not with gems at least.

From the readme:

https://github.com/seattlerb/hoe/blob/master/README.rdoc?plain=1#L30-L38

**Comment by velle** [comment]
Thanks for pointing to the docs :) I created this ticket in order to make aware that sow does not offer any of this information itself. 

IMHO any CLI tool should be able to give a few hints about what it is, and where to find more info. It could look like this:

```
$ sow -h
CLI tool part of the hoe project: https://github.com/seattlerb/hoe/
hoe version: 3.26
Usage: sow [options] project_name
Standard options:
    -t, --trunk                      Add project to subdir under 'trunk'.
    -d, --dev                        Add project to subdir under 'dev'.
    -s, --style style                Use template <style>.
    -h, --help                       Show this message.
```

**Comment by zenspider** [comment]
Sorry. No. Uninterested.
