### ISSUE TITLE
Gem install failing on shared server with rbenv or rvm

### ISSUE THREAD

**Issue by coorasse** [seattlerb/hoe#63]
If I try to install the gem on my shared server I obtain the following error:
`gem install hoe`
`Fetching: hoe-3.12.0.gem (100%)`
`ERROR:  While executing gem ... (Errno::EACCES)`
`Permission denied @ rb_sysopen /nfs/http7/user/.rvm/rubies/ruby2.1.0/lib/ruby/gems/2.1.0/gems/hoe-3.12.0/.autotest`

It is related to this issue also: https://github.com/seattlerb/minitest/issues/435
To solve it I had to manually download and recompile the gem as explained here:
http://forum.alwaysdata.com/viewtopic.php?pid=17733#p17733

**Comment by coorasse** [comment]
This is the same problem which affects minitest gem. The steps to reproduce the error are the same. I think this issue should be reopened.

**Comment by zenspider** [comment]
It's the exact same as seattlerb/minitest#435, so there's no reason for it to be here.

As described there, steps to reproduce are byzantine and far from minimal.

**Comment by coorasse** [comment]
The point is that this gem is affected by the same issue.The fact that the same issue affects something else doesn't mean that this one can be closed....we can mark it as a duplicate of the other one but the error is still there and open.

**Comment by zenspider** [comment]
It _does_ mean it can be closed. I work on both projects. Let me handle my projects my way.

**Comment by coorasse** [comment]
*Let me handle my projects my way*: your point ;)
