### ISSUE TITLE
Critique

### ISSUE THREAD

**Issue by JoshCheek** [seattlerb/hoe#70]
Sup sup. Decided to play with `hoe` based on https://twitter.com/the_zenspider/status/656611159764635648

Repo is [here](https://github.com/JoshCheek/playing-with-hoe). Wrote down some thoughts on the test task (readme part 1), played with a potentially viable alternate design (rakefile), documented what it was like to try and figure out how everything fit together (readme part 2).

There's a few quick wins in there, a quick wins, after you put a bit of thought into how best to address them, which will probably go a long way for anyone coming to these tools and not knowing where the entry point is (which, I suspect, is a hindrance to adoption at present), and a bit of "you know, I'm really not sure". Hopefully, at the very least, some insight :)

**Comment by zenspider** [comment]
Damn man... I wanted you to critique the test task, not the *whole damn thing*. Wow. Thank you!

This will take a while to digest. I'll put any followup questions I have here.
