### ISSUE TITLE
Wrong version of library installed.

### ISSUE THREAD

**Issue by duckinator** [seattlerb/hoe#72]
When running `rake newb` on the RubyGems repo on a fresh install, despite [telling hoe to use minitest ~> 4.0](https://github.com/rubygems/rubygems/blob/master/Rakefile#L62), I get:

```
C:/Users/marie/dev/ruby/rubygems/rubygems/lib/rubygems/dependency.rb:310:in `to_specs': Could not find 'minitest' (~> 4.0) - did find: [minitest-5.8.3] (Gem::MissingSpecVersionError)
```

Running `gem install minitest -v "~> 4.0"` then running `rake newb` again works. It appears to install the latest version of minitest, then expect minitest ~> 4.0. I've experienced this behavior on three different systems (two Windows, one Linux).

When I reported this on the [RubyGems repo](https://github.com/rubygems/rubygems/issues/1610), I was told to report it here.

**Comment by zenspider** [comment]
Just curious, but why MT4?

**Comment by duckinator** [comment]
I dunno, that's just what's specified atm. *shrug*

**Comment by zenspider** [comment]
This should be fixed in the next release. Thanks for the report!
