### ISSUE TITLE
Remove "." from a load path at test

### ISSUE THREAD

**Issue by junaruga** [seattlerb/hoe#74]
Hi,
I want to ask you about my concern.

I do not want to include "." as a load path at test command.

For example hoe is used in [puma](https://github.com/puma/puma).
"lib:bin:test:." is used as a load path.

```
$ bundle exec rake test
...
/usr/local/ruby-2.3.1/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_thread_pool.rb"; require "test/test_puma_server.rb"; require "test/test_app_status.rb"; require "test/test_rack_server.rb"; require "test/test_minissl.rb"; require "test/test_tcp_logger.rb"; require "test/test_unix_socket.rb"; require "test/test_tcp_rack.rb"; require "test/test_null_io.rb"; require "test/test_http10.rb"; require "test/test_rack_handler.rb"; require "test/test_persistent.rb"; require "test/test_ws.rb"; require "test/test_puma_server_ssl.rb"; require "test/test_config.rb"; require "test/test_iobuffer.rb"; require "test/test_integration.rb"; require "test/test_cli.rb"; require "test/test_http11.rb"' --
```

But I want to remove "." from the load path, because 

For example,
https://github.com/puma/puma/blob/master/test/test_http10.rb#L1

When we set `require 'test/testhelp'` or `require 'testhelp'`, both cases are available.
Because both "." and "test" are set as a load path. This is kind of duplicated path.
I want to prevent the case `require 'test/testhelp'`.

As a possible solution for that, I did set below code at the top of Rakefile to override the load path setting.

```
ENV["RUBY_FLAGS"] = "-w -I#{%w[lib bin test].join(File::PATH_SEPARATOR)}"
```

Then I got an error because of require 'path' format.

```
$ bundle exec rake test
...
/usr/local/ruby-2.3.1/bin/ruby -w -Ilib:bin:test -e 'require "rubygems"; require "minitest/autorun"; require "test/test_thread_pool.rb"; require "test/test_puma_server.rb"; require "test/test_app_status.rb"; require "test/test_rack_server.rb"; require "test/test_minissl.rb"; require "test/test_tcp_logger.rb"; require "test/test_unix_socket.rb"; require "test/test_tcp_rack.rb"; require "test/test_null_io.rb"; require "test/test_http10.rb"; require "test/test_rack_handler.rb"; require "test/test_persistent.rb"; require "test/test_ws.rb"; require "test/test_puma_server_ssl.rb"; require "test/test_config.rb"; require "test/test_iobuffer.rb"; require "test/test_integration.rb"; require "test/test_cli.rb"; require "test/test_http11.rb"' --
-e:1:in `require': cannot load such file -- test/test_thread_pool.rb (LoadError)
    from -e:1:in `<main>
```

I think below command is better than above one to prevent the error, though we can not see actual test files from the command.

```
$ ruby -w -Ilib:bin:test \
  -e 'require "rubygems"; require "minitest/autorun"; Dir.glob "./test/**/test_*.rb", &method(:require)' \
  --
```

Is it possible to change to this kind of logic?

Thank you.

**Comment by zenspider** [comment]
OK. So when you remove '.' from the path via `RUBY_FLAGS` you get an error because the test load mechanism is dependent upon that '.' being in the path. As such, nothing loads and it blows up. The way to fix this would be to change the loader to include `./` in the paths to load. Seems easy enough and I'm not against it.

That said, I'm having a hard time seeing why this matters. Why do you care how people load the test helper file? Does it really matter?

**Comment by zenspider** [comment]
anything?

**Comment by zenspider** [comment]
No response for over a year. Closing.

**Comment by junaruga** [comment]
> That said, I'm having a hard time seeing why this matters. Why do you care how people load the test helper file? Does it really matter?

I am sorry for so late response.
I was not notice the notification mail of this issue.

The reason this matters is,
For example on above case, when people include the mixture of both `test/testhelp` and `testhelp` in the code unintentionally, they want to know it as a bug.
But it is not very serious issue.

I am fine to close this.

I am sorry for the the late response again.
