### ISSUE TITLE
Dependency on Rake <12 causing difficulties with ruby 2.4

### ISSUE THREAD

**Issue by wwood** [seattlerb/hoe#77]
Hi,

Ruby 2.4 comes with rake 12.0.0, but according to the Rakefile, hoe is incompatible with rake 12. Is it possible to relax this requirement or are there still-existing reasons for it? I am completely ignorant of the history here, apologies if this question is naive.

Thanks, and happy new year. ben

**Comment by zenspider** [comment]
On Dec 26, 2016, 05:06 -0800, Ben J Woodcroft <notifications@github.com>, wrote:
> Ruby 2.4 comes with rake 12.0.0, but according to the Rakefile, hoe is incompatible with rake 12. Is it possible to relax this requirement or are there still-existing reasons for it? I am completely ignorant of the history here, apologies if this question is naive.

I haven’t looked into what made rake 12 hit a major rev, but it should probably be fine to relax the dependency. Wanna test it out and throw me a PR?

**Comment by zenspider** [comment]
Done via #78. Thanks!
