### ISSUE TITLE
how do i build it?

### ISSUE THREAD

**Issue by themaddoctor** [seattlerb/hoe#80]
How do I build hoe from these sources? there is not spec file in here.

No, I do NOT want a prepackaged thing.

**Comment by zenspider** [comment]
Build what? the gem?

```
9773 % rake -T | grep gem.*package
rake gem                   # package   # Build the gem file hoe-3.16.0.gem
rake install_gem           # package   # Install the package as a gem
```

so you can build the gem that way, or build AND install.

If that's not what you want, you'll have to be more clear.

**Comment by zenspider** [comment]
No response here or on https://github.com/seattlerb/minitest/issues/685

Should I close?

**Comment by zenspider** [comment]
OP doesn't want to communicate. Closing.
