### ISSUE TITLE
File name missing in warning message when README/History missing

### ISSUE THREAD

**Issue by kemonomachi** [seattlerb/hoe#81]
#### Description
Warning messages when README/History files are missing do not include the name of the missing file:

```
$ rake
**  is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
**  is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
```

In [hoe.rb, lines 650 and 651](https://github.com/seattlerb/hoe/blob/a629f7799f78f25b5f7f530aacc89903a10c739d/lib/hoe.rb#L650), when the README and History files can't be found in the manifest and no `.txt` or `.md` version is present in the project directory, `readme_file` and `history_file` are set to `nil`. This later on gives rise to the warnings above.

#### Proposed Solution
Making sure that `readme_file` and `history_file` are always set to sensible defaults (`{History,README}.txt`, as the [documentation](http://docs.seattlerb.org/hoe/Hoe.html#attribute-i-history_file) suggests) seems appropriate to me. Expected output would then be:

```
$ rake
** README.txt is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
** History.txt is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
```

If this is acceptable, I can create a pull request.

#### Background
Currently converting an existing project which has no `README.{md,txt}` or `History.{md,txt}`, nor any `Manifest.txt`.  Thought I'd just add Hoe to the Rakefile and follow the warnings/error messages to add the missing pieces. Found the warnings above somewhat confusing until I realized the connection to the missing files.

**Comment by zenspider** [comment]
If I `sow blah` and then remove its readme and history I currently get the following:

```
** README.rdoc is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
** History.rdoc is missing or in the wrong format for auto-intuiting.
   run `sow blah` and look at its text files
```

If I remove the Manifest, I get entirely different errors and will fix those separately.

So does this mean that it is handling your situation now?

**Comment by zenspider** [comment]
No response. Assuming it has been fixed and closing. Please reopen or file a new issue if you have problems in the future.
