### ISSUE TITLE
Can't release to rubygems anymore

### ISSUE THREAD

**Issue by saigkill** [seattlerb/hoe#87]
Sadly i can't deploy a gem to rubygems anymore. See the previous ticket: https://github.com/rubygems/rubygems/issues/2485

**Comment by zenspider** [comment]
That's a lot of text to read and doesn't seem obvious what it has to do with Hoe.

Help me out? What's the problem?

**Comment by zenspider** [comment]
No response from OP...

**Comment by zenspider** [comment]
No response. Closing.
