### ISSUE TITLE
Are there the complete list of URL names for Rubygems.org ?

### ISSUE THREAD

**Issue by maraigue** [seattlerb/hoe#91]
When I create a new gem template by Hoe, README.txt has places to specify URLs as

```
home  :: FIX (url)
code  :: FIX (url)
rdoc  :: FIX (url)
bugs  :: FIX (url)
```

However, as described in [https://guides.rubygems.org/specification-reference/#metadata](https://guides.rubygems.org/specification-reference/#metadata), there are more URL names that Rubygems.org accept. In addition, the names in the page above (e.g., "bug_tracker_uri", "changelog_uri", ...) are different from ones that Hoe produces (e.g., "home", "code", ...).
How are they processed? And are there the complete list of these URL names?

**Comment by zenspider** [comment]
You probably want to look at #86?

**Comment by zenspider** [comment]
#86 is merged and no response from OP. Closing.
