### ISSUE TITLE
versioning transparency

### ISSUE THREAD

**Issue by flavorjones** [seattlerb/hoe#95]
Hello! Long time Hoe user here, first time issue filer.

It's not clear to me what's in a release of Hoe. There are no tags on the repository, and there are not releases in Github.

Can I ask that the maintainers please create git tags for versions, as is conventional across many Ruby projects?

**Comment by ashmaroli** [comment]
Came here via Nokogiri..

@flavorjones Thought I'd lend you a hand in case you haven't figured it out by yourselves already. 
The changes between `v3.17.2` and `v3.18.0` can [be viewed here](https://github.com/seattlerb/hoe/compare/aaf747052197c60a7b1616e74ec3fcb7f695270f..dd02f882986b07bbe569aef49fd55e62a8a302c3).

**Comment by flavorjones** [comment]
@ashmaroli Thanks for providing that link, my concerns are more around the lack of clarity of which commits are in which version of Hoe.

**Comment by flavorjones** [comment]
e.g, if I had commits for 3.17 and 3.18 I could git bisect more easily when trying to diagnose a bug like #96.

**Comment by ashmaroli** [comment]
@flavorjones I understand your concern..
However, you can find the list of commits between `v3.17.2` and `v3.18.0` [here](https://github.com/seattlerb/hoe/compare/aaf747052197c60a7b1616e74ec3fcb7f695270f...dd02f882986b07bbe569aef49fd55e62a8a302c3).
Not sure, if they can help you *bisect*.

**Comment by flavorjones** [comment]
Thank you again, but I think you're still missing my underlying point which is that there is a lack of transparency about what commits are in what release.

**Comment by ashmaroli** [comment]
Not all Mike. I'm not countering your request for transparency here.
Just trying to help you come up with a patch for #96

**Comment by zenspider** [comment]
More "transparency" would require more use of git, which I'm reluctant to do. Currently everything I do is synced up to git via a cronjob, which unfortunately isn't that smart. Tags and such (releases are just tags) aren't created.

Everything I do is regular and well documented. @ashmaroli probably came up with the commits to diff between by doing a git blame (or log) on History.rdoc. It's the last thing I modify before I do any release.

**Comment by ashmaroli** [comment]
@zenspider What I did was `git blame` indeed but used the GitHub UI instead of the Command Line.
IMO, it shouldn't be this complicated to get a complete overview on what changed between releases.

**Comment by flavorjones** [comment]
@zenspider If you don't like the word "transparency" maybe we can substitute "obviousness"?

It sounds like your advice is: when I want to determine what commits are in which release, I should first go through the contents of the commits to History.rdoc (because the commit messages alone don't indicate what version is being prepped). Is that correct? That is moderately painful but I will work around it.

Side question: if you prefer to use perforce, what's preventing you from providing public access to your perforce repository? It feels like the primary challenge here is that your tooling isn't available to others.

**Comment by zenspider** [comment]
TADA: https://github.com/seattlerb/synchronizer/commit/e9da6aba91571fc401c7ffe77b9c6172c9311f13

and then:

https://github.com/seattlerb/hoe/releases

**Comment by ashmaroli** [comment]
Good job. @zenspider :tada:

**Comment by flavorjones** [comment]
Thanks, @zenspider, I very much appreciate it!
